name: development


on: pull_request


jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}


  check:
    name: Check formatting
    runs-on: ubuntu-latest
    needs: cancel
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: flutter format --dry-run . --set-exit-if-changed
      - name: Check lints
        run: flutter analyze
      - name: Run tests
        run: flutter test


# build, post task message etc.
